home:
  path: /
  methods: GET
  defaults: { _controller: AppBundle:Home:index }

about:
  path: /about
  methods: GET
  defaults: { _controller: AppBundle:Home:about }

contacts:
  path: /contacts
  methods: GET
  defaults: { _controller: AppBundle:Home:contacts }

example:
  path: /example
  methods: GET
  defaults: { _controller: AppBundle:Home:example }

categories-index:
  path:     /categories
  defaults: { _controller: AppBundle:Category:index }

categories-show:
  path:     /categories/{slug}
  defaults: { _controller: AppBundle:Category:show }
