home:
  path: /
  methods: GET
  defaults: { _controller: AppBundle:Home:index }

about:
  path: /about
  methods: GET
  defaults: { _controller: AppBundle:Home:about }

contacts:
  path: /contacts
  methods: GET
  defaults: { _controller: AppBundle:Home:contacts }

example:
  path: /example
  methods: GET
  defaults: { _controller: AppBundle:Home:example }
